### ISSUE TITLE
TODO 10-05-2016

### ISSUE THREAD

**Issue by npapratovic** [culexdoo/dentist-finder#1]
- obrisati simple.html
- basic-form.html
- preimenovati fajllove u jedninu, umjesto "dentists">"dentist", isto i za pacijente
- na pregledu svih zubara obrisati 4-7, i staviti izmišljena imena kod ostalih iznad
- na pregledu svih zubara akcijske tipke ne rade tj. ne vode na odgovarajuće podstranice
- na pregledu svih zubara generirati min. 25 zubara i implementirati https://datatables.net/ 
- nema pregled jednog zubara, ima samo edit
- treba imati 2 broja mobitela i 2 broja telefona
- textarea stajlati da ne piše "napomena o pacijentu" nego napomena o zubaru
- dodatiu prostor za podatke o ordinaciji: 
  ime, adresa, grad, email, broj telefona (sve po 2), oib, iban, radno vrijeme
- modal za brisanje zubara sa potvrdom želite li obrisati?
- fajlove formirati na slijedeći način: (isto je za doktore i za pacijente)
  add - edit - list
  a) dentist-add.html
  b) dentist-edit.html
  c) dentist-view.html
  d) dentist-list.html

**Comment by npapratovic** [comment]
- promjeniti logo aplikacije (u prilogu)
  ![hipsterlogogenerator_1462877009305](https://cloud.githubusercontent.com/assets/9073175/15143976/ee2dfb2e-16ac-11e6-92cb-e3b0a0431ecd.png)

**Comment by dinobelegic** [comment]
done
