### ISSUE TITLE
TODO - dashboard

### ISSUE THREAD

**Issue by npapratovic** [culexdoo/dentist-finder#2]
- Na dashboardu brojke - ukupno pacijenata, ukupno doktora, ukupno recenzija, ukupno upiza za posao
- ipis u po 2 kolone: zadnjih 10 pacijenata, zadnjih 10 zubara, zadnjih 10 upita, zadnjih 10 recenzija
- trebaju se ispisati osnovni podaci - redni broj, ime, prezime, datum, i brze akcije (pregled, uredi, obriši)

**Comment by dinobelegic** [comment]
done
