### ISSUE TITLE
TODO - pacijenti

### ISSUE THREAD

**Issue by npapratovic** [culexdoo/dentist-finder#4]
- neka bude 25 unosa
- search pomaknuti desno
- obrisati paginaciju dole, ostaviti od datatables paginaciju
- na patient-view promjeniti labelu iz "Doktor" u "Primarni zubar"
- zamjeniti mjesta desne i lijeve kolone, i u istaknuto treba biti 
  datum registracije, slika profila, broj recenzija, forma za unos bilješke o pacijentu
- na patient view treba biti gore desno button koji vodi na uredi tog pacijenta
- promjenit slikuz avatara i staviti neku lijepšu
- patient-add ova polja "Istaknuto" su duplirana, to je npotrebno, 
- treba stojati bilješka o pacijentu, ne blješka o zubaru

**Comment by dinobelegic** [comment]
done
