### ISSUE TITLE
TODO - zubari

### ISSUE THREAD

**Issue by npapratovic** [culexdoo/dentist-finder#5]
- kod pregleda zubara (i edit) nedostaju informacije o njegovoj ordinaciji : oib, adresa, kontakt broj ordinacije
- zamjeniti lijevu i desnu kolonu na pregledu / edit zubara

**Comment by npapratovic** [comment]
- generirati 25 zubara, isto Ivo Ivić, Marko Marković itd.

**Comment by dinobelegic** [comment]
done
