### ISSUE TITLE
TODO - upit za uslugu

### ISSUE THREAD

**Issue by npapratovic** [culexdoo/dentist-finder#6]
- preumenovati iz usluge u upiti
- pomaknuti dole tablicu da nije toliko zgurano gore
- generirati 25 unosa
- integirati datatables
- maknuti paginaciju dole
- pacijenti kadapredaju upit, oni popunjavaju svoje podatke: 
  ime, prezime, naziv oglasa, sadržaj, dokumente (do 5 komada) - i te informacije treba imati na pregledu
- kod upita je potrebno vidjeti i datum kreiranja
- popup sa brisanjem uputita ima u sebi podatke o zubaru

**Comment by dinobelegic** [comment]
done
