### ISSUE TITLE
Neki bugovi i izmjene

### ISSUE THREAD

**Issue by mariomikicvucak** [culexdoo/dentist-finder#8]
1. http://prntscr.com/b4e2jh - typo
2. http://prntscr.com/b4e3eb - Staviti lijepšu upload tipku, tu imaš puno primjera pa izaberi neki http://markusslima.github.io/bootstrap-filestyle/
   3.na dentist-list search bar staviti skroz desno. Treba prevesti "showing, previous, next" na hrv
3. Kad odeš na Kontrolna ploča onda ne radi link na pregled svih recenzija
4. Gdje je sustav poruka? Kako zubar odgovara na poruke?

**Comment by dinobelegic** [comment]
done
